### ISSUE TITLE
rgb -d .alice import test/rgb20-simplest.rgb Command Errors

### ISSUE THREAD

**Issue by UnCooe** [bitlightlabs/bitlight-rgb20-contract#10]
Following this tutorial, I have successfully retrieved the balances of Alice and Bob using the command rgb -d .alice utxos. However, when I try to run the command rgb -d .alice import test/rgb20-simplest.rgb, I encounter errors stating "Inventory file is corrupt, failed" and "Error: Entity not found". I'm sure the file test/rgb20-simplest.rgb exists and I have the same problem when following the command rgb import Examples/rgb20-simplest.rgb from the official documentation. I'm very frustrated and would like some guidance on what to do next.

**Comment by bitlightlabs-dev** [comment]
it is fixed in pr https://github.com/RGB-WG/rgb/pull/254
